// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef editorUI_h
#define editorUI_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include "level.h"
#include "loader.h"
#include <FL/Fl_BMP_Image.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_JPEG_Image.H>
#include "global.h"
#include <FL/Fl_Window.H>
#include "editor.h"
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Tabs.H>
#include "tilesetUI.h"
#include <FL/Fl_Browser.H>

class EditorUI {
public:
  EditorUI();
  Fl_Window *mainWindow;
  EditorView *editorView;
  static Fl_Menu_Item menu_[];
  static Fl_Menu_Item *menuNew;
  static Fl_Menu_Item *menuOpen;
private:
  inline void cb_menuOpen_i(Fl_Menu_*, void*);
  static void cb_menuOpen(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuSave;
  static Fl_Menu_Item *menuSaveAs;
private:
  inline void cb_menuSaveAs_i(Fl_Menu_*, void*);
  static void cb_menuSaveAs(Fl_Menu_*, void*);
public:
  TilesetUI *tilesetUI;
  Fl_Browser *BrowserLayer;
  void show(int argc, char **argv);
protected:
  char* filename; 
public:
  void loadTileset(const char* file);
};
#endif
